name: Continuous Deployment to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # ...

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      # Build and push Docker image (your existing steps)
      - name: Build and Push Docker Image
        run: |
              docker build -t snehap1408/wisecow:latest .
              docker push snehap1408/wisecow:latest

      # Deploy to Minikube
      - name: Deploy to Minikube
        run: |
            minikube start
            kubectl apply -f ./kubernetes/
